name: Test

on: [push, pull_request]

env:
  TERM: xterm

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ./.ghwf-$(uname).sh
        ./install.sh
        pip install pynvim
        pip install pytest pytest-timestamper
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        ./test/all.sh

    - name: Archive script logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.os }}
        path: test/*.log
