name: main
on: [push]
jobs:
  build:
    name: Build on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86
          - os: macos-latest
            arch: x86
          - os: windows-latest
            arch: x86
          - os: ubuntu-latest
            arch: aarch64
    steps:
      - uses: actions/checkout@v2
      - if: matrix.arch != 'x86'
        uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          install: |
            case "${{ matrix.os }}" in
              ubuntu*|jessie|stretch|buster)
                apt update -q -y
                apt install -q -y build-essential
                ;;
            esac
          run: make && rm build-log.txt
      - if: matrix.arch == 'x86'
        run: make
      - uses: romgrk/publish-to-github@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
