name: Tests on vim and neovim

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint code with Vint and shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install vint
        run: pip install --pre vim-vint
      - name: Lint vimscript files
        run: vint --warning --enable-neovim ./after ./autoload ./compiler ./ftdetect ./ftplugin ./indent ./syntax
      - name: Install shellcheck
        run: sudo apt-get -y install shellcheck
      - name: Lint shell scripts
        run: "shellcheck **/*.sh"

  tests:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        #neovim: [false, true]
        # When running vader tests in neovim under github's CI, it coredumps
        neovim: [false]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim or Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
      - name: Run Vader unit tests
        run: |
          if [ "${{ matrix.neovim }}" = "true" ]; then
            TESTVIM=nvim
          else
            TESTVIM=vim
          fi
          export TESTVIM
          ./test/run-tests.sh
